# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ad30d0e7f8bb68a2789c935cb1c1a679dbee80110f48c40c2b245401e6acfddb8cb2cc7219af835c3467f34e87ef7c1e7d69bd809c57f2bde4ed3c2a1751213

test:
  secret_key_base: e6a8a5be684de670a00e661ba6e534c176bb09182f287ca59b57c77812f71ff4534415d7d098f5b77120c53ae0ecd4bc7112728522ac1ddd0dbf4b5e36ed4971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
